apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ga1
  janus-idp.io/tekton: ga1
  backstage.io/kubernetes-id: ga1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ga1
resources:
- deployment.yaml
- route.yaml
- service.yaml
