apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ga1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ga1 
  name: ga1
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ga1
    weight: 100 
